package ir.cafebazaar.poolakey.constant

internal object BazaarIntent {

    const val RESPONSE_CODE = "RESPONSE_CODE"
    const val RESPONSE_RESULT_OK = 0
    const val RESPONSE_PURCHASE_DATA = "INAPP_PURCHASE_DATA"
    const val RESPONSE_SIGNATURE_DATA = "INAPP_DATA_SIGNATURE"
    const val RESPONSE_CONTINUATION_TOKEN = "INAPP_CONTINUATION_TOKEN"
    const val RESPONSE_PURCHASE_ITEM_LIST = "INAPP_PURCHASE_ITEM_LIST"
    const val RESPONSE_PURCHASE_DATA_LIST = "INAPP_PURCHASE_DATA_LIST"
    const val RESPONSE_DATA_SIGNATURE_LIST = "INAPP_DATA_SIGNATURE_LIST"
    const val RESPONSE_GET_SKU_DETAILS_LIST = "DETAILS_LIST"
    const val REQUEST_SKU_DETAILS_LIST = "ITEM_ID_LIST"
    const val RESPONSE_DYNAMIC_PRICE_TOKEN = "DYNAMIC_PRICE_TOKEN"
}
