buildscript {
    apply from: "$rootDir/version-manager.gradle"
    repositories {
        google()
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$pluginVersions.gradle"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$libraryVersions.kotlin"
        classpath "org.jetbrains.dokka:dokka-gradle-plugin:$pluginVersions.dokka"
        classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:$pluginVersions.detekt"
    }
}

allprojects {
    apply from: "$rootDir/version-manager.gradle"
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

subprojects {
    apply plugin: "io.gitlab.arturbosch.detekt"
    detekt {
        toolVersion = pluginVersions.detekt
        source = files("${rootDir}")
        config = files("${rootDir}/detekt.yml")
    }
    tasks.withType(io.gitlab.arturbosch.detekt.Detekt).configureEach {
        exclude("**/resources/**", "**/build/**")
        reports {
            xml.required = false
            txt.required = false
            sarif.required = false
            md.required = false
            html {
                required = true
                outputLocation = file("${rootDir}/build/reports/detekt.html")
            }
        }
    }
}
