package com.phelat.poolakey.constant

internal object BazaarIntent {

    const val RESPONSE_CODE = "RESPONSE_CODE"
    const val RESPONSE_RESULT_OK = 0
    const val RESPONSE_PURCHASE_DATA = "INAPP_PURCHASE_DATA"
    const val RESPONSE_SIGNATURE_DATA = "INAPP_DATA_SIGNATURE"
    const val RESPONSE_CONTINUATION_TOKEN = "INAPP_CONTINUATION_TOKEN"
    const val RESPONSE_PURCHASE_ITEM_LIST = "INAPP_PURCHASE_ITEM_LIST"
    const val RESPONSE_PURCHASE_DATA_LIST = "INAPP_PURCHASE_DATA_LIST"
    const val RESPONSE_DATA_SIGNATURE_LIST = "INAPP_DATA_SIGNATURE_LIST"

}
